#include <stdio.h>
#include <stdlib.h>
#include <string.h>  //for string operations

// Global Definition

struct emp
{
    char name[80];          //name of employee
    int emp_id;             //employee id generated by program
    char join_date[10];     //joining date of employee
    int sal;                //employee salary
    char password[32];      //age of employee

    struct personalinfo     //personal information
    {

        char address[150];  //address of employee
        char emailid[20];   //Email id of employee
        char ph_no[10];     //employee phone number
        char emerph_no[10]; //employee's emergency phone number

    }pi;                    //Nested structure personal info variable creation

};

/* Main function started */

int main()
{
    //Variables Declarations
    struct emp e;
    int recsize;        // size of each record of employee
    int tot_rec;        // it will be used to calculate total no of records in the file

    int c=0;
    FILE *fp=NULL;
    FILE *ft=NULL;      // file pointers

    char another ;
    int choice ;

    char password[32];  // string to store name of the employee used to compare with original before any kind of editing
    int id;             // store id of the employee used to compare with original before any kind of editing

    //FUNCTION DECLARATIONS
    void swap(struct emp* ,struct emp*);    // it is used in sorting functions to swap 2 records

    int checkentry(int,char[32],FILE*);     // it is used to check if id and password are present in list or not

    struct emp read_rec();                  // To read records from user

    void view_rec(struct emp);              // To print record

    void sort_name_asc(FILE *,int );        // To sort name wise in ascending
    void sort_name_desc(FILE *,int );       // To sort name wise in descending

    void sort_sal_asc(FILE *,int );         // To sort salary wise in ascending
    void sort_sal_desc(FILE *,int );        // To sort salary wise in descending

    void sort_jd_asc(FILE *,int );          // To sort Joining Date wise in ascending
    void sort_jd_desc(FILE *,int );         // To sort Joining Date wise in descending


    fp = fopen("EMP.DAT","rb+");

    if(fp == NULL)
    {
        fp = fopen("EMP.DAT","wb+");
        if(fp == NULL)
        {
            printf("Cannot open file");
            exit(1);
        }
    }   /* open the file in binary read and write mode
        * if the file EMP.DAT already exists then it open that file in read write mode
        * if the file doesn't exit it simply create a new copy
        */

    // size of each` record i.e. size of structure emp variable (e)
    recsize = sizeof(e);

    // infinite loop continues till break statement occurs
    while(1)
    {

        printf("\n\n 1. Add Record"); // option for add record
        printf("\n 2. List Records"); // option for showing existing record
        printf("\n 3. Modify Records"); // option for modifying record      // ask password and id before editing
        printf("\n 4. Delete Records"); // option for deleting record       // ask password and id before deleting
        printf("\n 5. Search Records"); // option for searching record
        printf("\n 6. Sort Records"); // option for sort record             //3 options by name ,join date, salary
        printf("\n 7. Change password"); // option for changing password of record      // ask password and id before changing
        printf("\n 8. Exit"); // exit from the program
        printf("\n Your Choice: "); // enter the choice 1,2,3,4,5,6,7,8
        scanf("%d",&choice);

        switch(choice)

        {
            case 1://ADD RECORD
                    fseek(fp,0,SEEK_END); // search the file and move cursor to end of the file
                    // here 0 indicates moving 0 distance from the end of the file

                    another = 'y';
                    while(another == 'y')  // till user want to add another record

                    {
                        e=read_rec();       //Function Call

                        fwrite(&e,recsize,1,fp); // write the record in the file

                        printf("\n Add another record(y/n) ");  // if user want to add another record

                        fflush(stdin);

                        another = getchar();

                    }
                    break;

            case 2://VIEW or LIST

                    rewind(fp); //this moves file cursor to start of the file
                    if(fread(&e,recsize,1,fp)==0)   // If list is empty
                        printf(" List is empty");
                    rewind(fp);
                    while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                    {
                        // printing employee records
                        view_rec(e);        // Function Call
                    }

                    break;

            case 3: //MODIFY
                    rewind(fp); //this moves file cursor to start of the file
                    if(fread(&e,recsize,1,fp)==0)   // If list is empty
                        printf(" List is empty");
                    else
                    {
                        another = 'y';
                        while(another == 'y')
                        {
                            printf("\n Enter the employee id to modify : ");
                            scanf("%d",&id);
                            fflush(stdin);
                            printf("\n To modify you need to enter password: ");
                            scanf("%s",password);
                            rewind(fp);
                            if(checkentry(id,password,fp))
                            {
                                rewind(fp);
                                while(fread(&e,recsize,1,fp))  // fetch all record from file
                                {
                                    if((e.emp_id==id)&&(strcmp(password,e.password)==0))  //if id and password matches
                                    {
                                        e=read_rec();
                                        fseek(fp,-recsize,SEEK_CUR); // move the cursor 1 step back from current position
                                        fwrite(&e,recsize,1,fp); // override the record
                                        printf("\n Modification Successful ");
                                        break;
                                    }
                                }
                            }
                            else
                                printf("\n No Record Found");

                            printf("\n Modify another record(y/n)");
                            fflush(stdin);
                            another = getchar();
                        }
                    }
                    break;

             case 4://DELETE
                    rewind(fp); //this moves file cursor to start of the file
                    if(fread(&e,recsize,1,fp)==0)   // If list is empty
                        printf(" List is empty");
                    else
                    {
                        another = 'y';
                        while(another == 'y')
                        {
                            printf("\n Enter the employee id to delete : ");
                            scanf("%d",&id);
                            fflush(stdin);
                            printf("\n To delete you need to enter employee password: ");
                            scanf("%s",password);

                            ft = fopen("Temp.dat","wb");  // create a intermediate file for temporary storage
                            rewind(fp); // move record to starting of file
                            if(checkentry(id,password,fp))
                            {
                                rewind(fp);
                                while(fread(&e,recsize,1,fp) == 1)  // read all records from file
                                {
                                    if((e.emp_id==id)&&(strcmp(password,e.password)==0))  //if id and password matches
                                        continue;
                                    else
                                        fwrite(&e,recsize,1,ft); // move all records except the one that is to be deleted to temp file
                                }

                                fclose(fp);
                                fclose(ft);

                                remove("EMP.DAT"); // remove the original file
                                rename("Temp.dat","EMP.DAT"); // rename the temp file to original file name

                                fp = fopen("EMP.DAT", "rb+");
                            printf("\n Record Deleted Successfully ");
                            printf("\n Delete another record(y/n)");

                            fflush(stdin);

                            another = getchar();
                            }
                            else
                            {
                                printf("\n No Record Found");
                                printf("\n Delete another record(y/n)");
                                fflush(stdin);
                                another = getchar();
                            }
                        }
                    }
                    break;

            case 5://SEARCH
                    tot_rec=0;
                    rewind(fp);
                    while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                    {
                        // printing employee records
                        tot_rec++;
                    }

                    if(tot_rec==0)
                        printf("List is empty");
                    else
                    {
                        another = 'y';
                        while(another == 'y')
                        {
                            fflush(stdin);

                            printf("\n Enter the employee id to search : ");
                            scanf("%d",&id);

                            rewind(fp);
                            c=0;
                            while(fread(&e,recsize,1,fp))  // fetch all record from file
                            {
                                c++;
                                if((e.emp_id==id))  //if id and password matches
                                {
                                    fflush(stdin);
                                    printf("\n Record found . Do you want to see it ?(y/n) ");
                                    another=getchar();
                                    if(another=='y')
                                    {
                                        view_rec(e);
                                        break;
                                    }
                                    else if(another=='n')
                                        break;
                                    else
                                        printf("\n Invalid Selection");
                                }
                                if(c==tot_rec)
                                    printf("\n No record found.");
                            }

                            printf("\n Search another record(y/n)");
                            fflush(stdin);
                            another = getchar();
                        }
                    }
                    break;

            case 6://SORT
                    tot_rec=0;
                    rewind(fp);
                    while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                    {
                        // printing employee records
                        tot_rec++;
                    }

                    if(tot_rec==0)
                        printf("List is empty");
                    else
                    {
                        printf("\n 1. To Sort the list based on Employee Name\n 2. To Sort the list based on Salary\n 3. To Sort the list based on Join Date  \n Your Choice : ");
                        scanf("%d",&choice);
                        rewind(fp);
                        switch(choice)
                        {
                            case 1 ://sort name wise

                                    printf("\n 1. To Sort the list based on Employee name in Ascending order\n 2. To Sort the list based on Employee name in Descending order \n Your Choice : ");
                                    scanf("%d",&choice);

                                    switch(choice)
                                    {
                                        case 1 ://sort name ascending

                                                sort_name_asc(fp,tot_rec);         //function call

                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                                    view_rec(e);
                                                }                //function call
                                                break;
                                        case 2 ://sort name descending
                                                sort_name_desc(fp,tot_rec);        //function call
                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                                    view_rec(e);
                                                }                //function call
                                                break;

                                        default : printf("\n Invalid entry");
                                    }
                                    break;

                            case 2 ://sort salary wise

                                    printf("\n 1. To Sort the list based on Salary in Ascending order\n 2. To Sort the list based on Salary in Descending order \n Your Choice : ");
                                    scanf("%d",&choice);
                                    switch(choice)
                                    {
                                        case 1 ://sort salary ascending

                                                sort_sal_asc(fp,tot_rec);        //function call
                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                                    view_rec(e);
                                                }                //function call
                                                break;
                                        case 2 ://sort salary descending
                                                sort_sal_desc(fp,tot_rec);        //function call
                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                                    view_rec(e);
                                                }                //function call
                                                break;
                                        default : printf("invalid entry");
                                    }
                                    break;
                            case 3 ://sort joining date wise

                                    printf("\n 1. To Sort the list based on Join Date in Ascending order\n 2. To Sort the list based on Join Date in Descending order \n Your Choice : ");
                                    scanf("%d",&choice);
                                    switch(choice)
                                    {
                                        case 1 ://sort join date ascending

                                                sort_jd_asc(fp,tot_rec);        //function call
                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                                    view_rec(e);
                                                }                //function call
                                                break;
                                        case 2 ://sort join date descending
                                                sort_jd_desc(fp,tot_rec);        //function call
                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                                    view_rec(e);
                                                }                //function call
                                                break;
                                        default : printf("invalid entry");
                                    }
                                    break;


                            default : printf("invalid entry");
                        }
                    }
                    break;
            case 7://Change Password
                    rewind(fp); //this moves file cursor to start of the file
                    if(fread(&e,recsize,1,fp)==0)   // If list is empty
                        printf(" List is empty");
                    else
                    {
                        another = 'y';
                        while(another == 'y')
                        {

                            printf("\n Enter the employee id to change password : ");
                            scanf("%d",&id);

                            fflush(stdin);
                            printf("\n To modify you need to enter old password: ");
                            scanf("%s",password);
                            rewind(fp);
                            if(checkentry(id,password,fp))
                            {
                                rewind(fp);
                                while(fread(&e,recsize,1,fp))  // fetch all record from file
                                {
                                    if((e.emp_id==id)&&(strcmp(password,e.password)==0))  //if id and password matches
                                    {
                                        fflush(stdin);

                                        printf("\n Enter New Password :- ");
                                        scanf("%s",e.password);
                                        while(1)
                                        {

                                            fflush(stdin);

                                            printf("\n Confirm New Password :- ");
                                            scanf("%s",password);

                                            if(strcmp(e.password,password)==0)
                                                break;
                                            else
                                            {
                                                printf("\n Enter New Password :- ");
                                                scanf("%s",e.password);
                                            }
                                        }
                                        fseek(fp,-recsize,SEEK_CUR); // move the cursor 1 step back from current position
                                        fwrite(&e,recsize,1,fp); // override the record
                                        printf("\n Your Password is changed Successfully ");
                                        break;
                                    }
                                }
                            }
                            else
                                printf("\n No record found");
                            printf("\n Change password of another record (y/n)");
                            fflush(stdin);
                            another = getchar();
                        }
                    }
                    break;
            case 8:

                fclose(fp);  // close the file
                exit(0); // exit from the program

            default:printf("Invalid Entry");

        }
    }
    return 0;
}

void swap(struct emp *x,struct emp *y)
{
    struct emp temp;
    temp = *x;
    *x = *y;
    *y = temp;
}


struct emp read_rec()
{
    struct emp e;
    char password[32] ;

    fflush(stdin);

    printf("\n Enter Employee Name :- ");
    scanf("%[^\n]s",e.name);

    printf("\n Enter Employee id :- ");
    scanf("%d",&e.emp_id);

    printf("\n Enter Employee Joining Date (dd/mm/yyyy):- ");
    scanf("%s",e.join_date);

    printf("\n Enter Employee Salary :- ");
    scanf("%d",&e.sal);
    fflush(stdin);

    printf("\n Enter Password :- ");
    scanf("%s",e.password);
    while(1)
    {

        fflush(stdin);

        printf("\n Confirm Password :- ");
        scanf("%s",password);

        if(strcmp(e.password,password)==0)
            break;
        else
        {
            printf("\n Enter Password :- ");
            scanf("%s",e.password);
        }
    }

    fflush(stdin);

    printf("\n Enter Employee Address :- ");
    scanf("%s",e.pi.address);

    fflush(stdin);

    printf("\n Enter Employee Email id :- ");
    scanf("%s",e.pi.emailid);

    printf("\n Enter Employee Phone number :- ");
    scanf("%s",e.pi.ph_no);

    printf("\n Enter Employee Emergency Phone number :- ");
    scanf("%s",e.pi.emerph_no);
    return e;
}

void view_rec(struct emp e)
{
    printf("\n Employee name : %s ",e.name);
    printf("\n Employee ID : %d ",e.emp_id);
    printf("\n Employee Joining Date (dd/mm/yyyy) : %s ",e.join_date);
    printf("\n Employee Salary : %d ",e.sal);
    printf("\n Employee Address : %s ",e.pi.address);
    printf("\n Employee Email ID : %s ",e.pi.emailid);
    printf("\n Employee Phone Number : %s ",e.pi.ph_no);
    printf("\n Employee Emergency Phone Number : %s ",e.pi.emerph_no);
    printf("\n Employee PASSWORD : %s\n\n",e.password);
}

void sort_sal_asc(FILE *fp,int n)
{
    struct emp e;
    struct emp f;
    int i , j;
    long int recsize=sizeof(e);

    for(i = 0 ; i<n-1 ; i++)
    {
        fread(&e,recsize,1,fp);
        fread(&f,recsize,1,fp);

        if(e.sal > f.sal)
        {
            swap(&e,&f);        //function call

            fseek(fp,-2*recsize,SEEK_CUR);
            fwrite(&e,recsize,1,fp);
            fwrite(&f,recsize,1,fp);
            rewind(fp);
            i=-1;
        }

        fseek(fp,-recsize,SEEK_CUR);

    }
}

void sort_sal_desc(FILE *fp,int n)
{
    struct emp e;
    struct emp f;
    int i , j;
    long int recsize=sizeof(e);

    for(i = 0 ; i<n-1 ; i++)
    {
        fread(&e,recsize,1,fp);
        fread(&f,recsize,1,fp);

        if(e.sal < f.sal)
        {
            swap(&e,&f);        //function call

            fseek(fp,-2*recsize,SEEK_CUR);
            fwrite(&e,recsize,1,fp);
            fwrite(&f,recsize,1,fp);
            rewind(fp);
            i=-1;
        }

        fseek(fp,-recsize,SEEK_CUR);

    }
}

void sort_name_asc(FILE *fp,int n)
{
    struct emp e;
    struct emp f;
    int i , j;
    long int recsize=sizeof(e);

    for(i = 0 ; i<n-1 ; i++)
    {
        fread(&e,recsize,1,fp);
        fread(&f,recsize,1,fp);

        if(strcmp(e.name, f.name) > 0)
        {
            swap(&e,&f);        //function call

            fseek(fp,-2*recsize,SEEK_CUR);
            fwrite(&e,recsize,1,fp);
            fwrite(&f,recsize,1,fp);
            rewind(fp);
            i=-1;
        }
        else
            fseek(fp,-recsize,SEEK_CUR);

    }
}

void sort_name_desc(FILE *fp,int n)
{
    struct emp e;
    struct emp f;
    int i , j;
    long int recsize=sizeof(e);

    for(i = 0 ; i<n-1 ; i++)
    {
        fread(&e,recsize,1,fp);
        fread(&f,recsize,1,fp);

        if(strcmp(e.name, f.name) < 0)
        {
            swap(&e,&f);        //function call

            fseek(fp,-2*recsize,SEEK_CUR);
            fwrite(&e,recsize,1,fp);
            fwrite(&f,recsize,1,fp);
            rewind(fp);
            i=-1;
        }

        fseek(fp,-recsize,SEEK_CUR);

    }
}

void sort_jd_asc(FILE *fp,int n)
{
    struct emp e;
    struct emp f;
    int i , j;
    int recsize=sizeof(e);
    double edatesum,fdatesum;
    double calc_datesum(struct emp);

    for(i = 0 ; i<n-1 ; i++)
    {
        fread(&e,recsize,1,fp);
        fread(&f,recsize,1,fp);

        edatesum=calc_datesum(e);
        fdatesum=calc_datesum(f);

        if(edatesum > fdatesum)
        {
            swap(&e,&f);        //function call

            fseek(fp,-2*recsize,SEEK_CUR);
            fwrite(&e,recsize,1,fp);
            fwrite(&f,recsize,1,fp);
            rewind(fp);
            i=-1;
        }

        fseek(fp,-recsize,SEEK_CUR);

    }
}

void sort_jd_desc(FILE *fp,int n)
{
    struct emp e;
    struct emp f;
    int i , j;
    int recsize=sizeof(e);
    double edatesum,fdatesum;
    double calc_datesum(struct emp);

    for(i = 0 ; i<n-1 ; i++)
    {
        fread(&e,recsize,1,fp);
        fread(&f,recsize,1,fp);

        edatesum=calc_datesum(e);
        fdatesum=calc_datesum(f);

        if(edatesum < fdatesum)
        {
            swap(&e,&f);        //function call

            fseek(fp,-2*recsize,SEEK_CUR);
            fwrite(&e,recsize,1,fp);
            fwrite(&f,recsize,1,fp);
            rewind(fp);
            i=-1;
        }

        fseek(fp,-recsize,SEEK_CUR);

    }
}


double calc_datesum(struct emp e)
{
    int year;
    int month;
    int day;
    double sum;

    year = 1000*(e.join_date[6]-48) + 100*(e.join_date[7]-48) + 10*(e.join_date[8]-48) + (e.join_date[9]-48) ;
    month = 10*(e.join_date[3]-48) + (e.join_date[4]-48) ;
    day  = 10*(e.join_date[0]-48) + (e.join_date[1]-48) ;
    sum = 1000000*year+10000*month+100*day;
    return(sum);
}

int checkentry(int id , char password[32] ,FILE *fp)
{
    struct emp e;
    int recsize=sizeof(e);

    while(fread(&e,recsize,1,fp))  // fetch all record from file
    {
        if((e.emp_id==id)&&strcmp(e.password,password)==0)  //if id and password matches
        {
            return 1;
        }
    }
    return 0;
}






